### ISSUE TITLE
maybe, just return "mock str." 

### ISSUE THREAD

**Issue by pengpj** [chaitin/log4j2-vaccine#1]
https://github.com/chaitin/log4j2-vaccine/blob/ea7491cd64fd0c7ec5b0ee45fd84e85880c75f3b/agent/src/main/java/com/chaitin/vaccine/agent/transform/JndiManagerTransformer.java#L48

**Comment by pengpj** [comment]
谁会在日志构架里面用 jndi 啊

**Comment by d1nfinite** [comment]
done https://github.com/chaitin/log4j2-vaccine/commit/869c024a268d10b84ded0616d9ab1f792bb855ab

**Comment by d1nfinite** [comment]
done https://github.com/chaitin/log4j2-vaccine/commit/869c024a268d10b84ded0616d9ab1f792bb855ab
